sonar.projectKey=2026c1-pdes-grupo4_backend
sonar.projectName=CTH - Compra tu Hogar (Backend)
sonar.projectVersion=0.0.1
sonar.organization=2026c1-pdes-grupo4

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=\
  **/dto/**,\
  **/config/**,\
  **/*Application*,\
  **/seed/**,\
  **/*Repository*,\
  **/*Mapper*,\
  **/auth/Jwt*,\
  **/common/error/**,\
  **/picture/**

sonar.sourceEncoding=UTF-8
