package ar.edu.unq.backend.common.error;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    USER_NOT_FOUND,
    AGENCY_NOT_FOUND,
    ADMIN_USER_NOT_FOUND,
    PROPERTY_NOT_FOUND,
    AGENCY_PROPERTY_NOT_FOUND,
    FAVORITE_NOT_FOUND,

    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    PUBLICATION_ALREADY_FAVORITED,
    PUBLICATION_ALREADY_EXISTS_FOR_AGENCY,
    PROPERTY_ALREADY_SOLD,

    CANNOT_MODIFY_OTHER_FAVORITE,
    CANNOT_DELETE_OTHER_FAVORITE,
    CANNOT_MODIFY_OTHER_PUBLICATION,
    CANNOT_DELETE_OTHER_PUBLICATION,
    SOLD_PUBLICATION_CANNOT_BE_DELETED,
    SOLD_PROPERTY_CANNOT_BE_DELETED,
    PROPERTY_HAS_ACTIVE_PUBLICATIONS,

    INVALID_PROPERTY_TYPE,
    INVALID_PRICE_RANGE,
    INVALID_SCORE,
    INVALID_REQUEST,

    FORBIDDEN,
    UNAUTHORIZED,
    INTERNAL_ERROR
}

